[tool.poetry]
name = "pycounts"
version = "0.1.0"
description = "A package for counting the number of words"
authors = ["Vik Geerawor <sgeerawor@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11"
matplotlib = ">=3.7.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
